### PR TITLE
Blacklight 6.x upgrade

### PR DESCRIPTION
**Pull request by mejackreed**
I'm not really happy with the way the routing turned out in 0577050d75e4100b120f0b8afbeb46cb8921223a and 0965390c01e4bd7cbbd301a912ea23a2d09069af. This probably needs some refinement.

### CODE REVIEW

**Comment by eliotjordan** [comment]
@mejackreed In regards to your earlier comment about commits (with new hashes) a159de3 and 241b880, how would you improve these? And what is causing the issues with the engine not mounting routes?

**Comment by mejackreed** [comment]
@eliotjordan Not sure.. was mostly focused on just getting it working. The routes would show up in `/rails/info` but wouldn't be accessible by the application? Maybe I wasn't referencing them in isolation correctly? ala `geoblacklight.downloads_path`?

I think the problem with merging as is, is the fact that we can't add routes down the road without an adopter adding them into their local application.

**Comment by eliotjordan** [comment]
@mejackreed Yeah. That makes sense. I'm installing this branch into pulmap right now. I'll see what shakes out.

**Comment by eliotjordan** [comment]
Spatial search isn't working for me on this branch. It looks as if the bbox param isn't being passed to solr.

**Comment by eliotjordan** [comment]
Just need to add `include Geoblacklight::SpatialSearchBehavior` to the SearchBuilder model.

**Comment by eliotjordan** [comment]
Uhh. Coverage decreased 33.7% after updating capybara and rspec-rails? Hmmm...

**Comment by eliotjordan** [comment]
Princeton give this a 👍.

**Pull request merged**
