### PR TITLE
FeatureLayer: bug fixes for missing icons and empty feature layer results

### LINKED ISSUE #706: ESRI feature layers missing marker icons
This is an issue with leaflet or leaflet-rails.
https://github.com/axyjo/leaflet-rails/issues/81

Appears when viewing this fixture: https://github.com/geoblacklight/geoblacklight/blob/master/spec/fixtures/solr_documents/esri-feature-layer.json

### LINKED ISSUE #717: FeatureLayer - Empty JSON request results
### Descriptive summary

GeoBlacklight 1.9+ exhibits an error, similar to #715, where click events and API query calls for FeatureLayer points and polygons return no feature results.

### Expected behavior

Expect to remotely fetch feature click data successfully.

### Actual behavior

Many requests are returning zero results.

### Steps to reproduce the behavior

1. Checkout master
2. bundle exec rake geoblacklight:server
3. Visit http://localhost:3000/catalog/f406332e63eb4478a9560ad86ae90327_18
4. No markers will present. Move your mouse across the map and you'll see it turn into a pointer. Try clicking that area.

You'll see a console error "Cannot read property 'properties' of undefined". If you look at your XHR requests, you'll see [this json request](https://geodata.md.gov/imap/rest/services/Transportation/MD_Transit/FeatureServer/18/query?returnGeometry=false&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22x%22%3A-76.932817%2C%22y%22%3A38.748261%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPoint&spatialRel=esriSpatialRelIntersects&f=geojson) was made.

### Related work

This issue is undoubtedly related to our recent GBL 1.9 leaflet and esri-leaflet updates:
#679

This issue is also similar to #715

### PR DESCRIPTION
**Pull request by ewlarson**
This PR fixes two FeatureLayer issues by vendorizing a Rails asset_url "friendly" version of Leaflet 1.4.0. It's essentially a local GBL version of the leaflet-rails gem, which increasingly appears to be unmaintained (open PRs, unmanaged issues, Leaflet 1.3).

Using Rails' asset_url helper to wrap Leaflet's default icon paths, we bypass a non-trivial [Leaflet icon path regex bug](https://github.com/Leaflet/Leaflet/issues/4968) related to asset pipeline/webpack fingerprint complexity.

Adds Leaflet 1.4.0 assets to vendor/assets/javascript, vendor/assets/stylesheets, and vendor/assets/images. Appends vendor/assets/images to Rails.application.config.assets.path in initializers/assets.rb

Fixes #717 
Fixes #706

### CODE REVIEW

**Comment by ewlarson** [comment]
Oh rubocop...

**Comment by eliotjordan** [comment]
@mejackreed This is a fairly large change, but I don't think most implementors will notice. How does this look to you?

**Comment by mejackreed** [comment]
/shrug ? I mean I don't like having to now maintain Leaflet internally, but recognize the issues around Leaflet-Rails. So I don't really have a better solution. 😿

**Comment by eliotjordan** [comment]
Hopefully this won't be permanent. @ewlarson identified a method for fixing this using webpacker. When we go all in with it in a future release, we can remove our vendored copy and manage it with a package.json file.

**Pull request merged**
