### PR TITLE
update error message and test

### PR DESCRIPTION
**Pull request by the-codetrane**
PR for https://github.com/geoblacklight/geoblacklight/issues/1240

### CODE REVIEW

**Review by thatbudakguy — APPROVED** [review]
looks good!

**Comment by the-codetrane** [comment]
@thatbudakguy not entirely sure why, but it looks like there are a couple of jobs that are not reporting back to pass this PR?

**Comment by eliotjordan** [comment]
@the-codetrane The PR needs a rebase against main to bring in the new Ruby 3.2 checks.

**Comment by eliotjordan** [comment]
@the-codetrane It should be fine. I merged it.

**Pull request merged**
