### PR TITLE
update jettywrapper to latest

### PR DESCRIPTION
**Pull request by mejackreed**

### CODE REVIEW

**Comment by eliotjordan** [comment]
I'm all for merging this commit. Is there a reason to wait?

**Comment by mejackreed** [comment]
No :shipit: !!

**Comment by mejackreed** [comment]
@eliotjordan I meant, yes please someone merge it!

**Comment by eliotjordan** [comment]
My emoji skills are weak, but I think that means "merge with gusto".

**Comment by mejackreed** [comment]
:smile: @eliotjordan

**Pull request merged**
