### PR TITLE
CartoDB basemaps display higher resolution on retina screen

### PR DESCRIPTION
**Pull request by eliotjordan**
This PR makes basemaps higher resolution when displayed on a retina monitor. Not sure how I feel about it. They look very sharp (obvs), but are harder to read and take a noticeably longer amount of time to load.

### CODE REVIEW

**Comment by eliotjordan** [comment]
...and every feature test is broken.

**Comment by mejackreed** [comment]
hmm.. I say let an adopter do this in override type way

**Comment by mejackreed** [comment]
Also could this work instead? https://github.com/leaflet-extras/leaflet-providers#retina-tiles

Using `{retina}`

**Comment by eliotjordan** [comment]
Thanks for the tip @mejackreed. Force pushed a new version of this PR that is far simpler. Adopters can simply indicate that they want to use retina basemaps by overriding `GeoBlacklight.Basemaps` and setting `detectRetina: true`.

**Pull request merged**
