### PR TITLE
remove route adds from generator

### LINKED ISSUE #287: Move routes out of generator and into Geoblacklight::Routes
Needs #285 merged first

This will allow adopters to upgrade easier to new features/routes that need to be added without configuring them manually.

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #287 

So new routes can added or modified in GeoBlacklight without causing adopters too much pain

This might be controversial... what do others think?

### CODE REVIEW

**Comment by gravesm** [comment]
:+1: on this change. Are there any objections?

**Comment by eliotjordan** [comment]
This is a good modification. I support it.

**Comment by eliotjordan** [comment]
Tests passed on my machine, and I was able to add a test route.

**Comment by gravesm** [comment]
Yeah, hearing no objections, I'm going to go ahead and merge.

**Comment by mejackreed** [comment]
:+1:

**Pull request merged**
