### PR TITLE
adds SVGs for long institution names and updates fixtures

### PR DESCRIPTION
**Pull request by karenmajewicz**
This PR adds SVG icons for BTAA institutions with full names (University of Minnesota) instead of short (Minnesota). It also updates the fixtures to match.

I left copies of the icons with the old names so existing metadata files will still work.

### CODE REVIEW

**Comment by karenmajewicz** [comment]
addresses #933

**Comment by karenmajewicz** [comment]
Local test failures

Failures:
  1) spatial search results overlap ratio result bboxes fully contained, overlap ratio applied to relevancy
     Failure/Error: results.index(id) + 1
     
     NoMethodError:
       undefined method `+' for nil:NilClass
     # ./spec/features/search_results_overlap_ratio_spec.rb:55:in `position_in_result_page'
     # ./spec/features/search_results_overlap_ratio_spec.rb:16:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 36.6 seconds (files took 2.2 seconds to load)
349 examples, 1 failure, 7 pending

Failed examples:

rspec ./spec/features/search_results_overlap_ratio_spec.rb:5 # spatial search results overlap ratio result bboxes fully contained, overlap ratio applied to relevancy

**Comment by karenmajewicz** [comment]
Oh, I now see that a spec file calls the "Minnesota" provenance as a check. I will adjust that and re-test.

**Review by ewlarson — APPROVED** [review]
Nice work here and glad you hunted down the spec error!

**Comment by karenmajewicz** [comment]
Hot diggity. Thanks.

**Pull request merged**
