### PR TITLE
Leaflet upgrade for master

### PR DESCRIPTION
**Pull request by ewlarson**
* Bump leaflet-rails, esri-leaflet, and leaflet-iiif to their most current release versions
* Fix upgrade issues for the opacity slider
* Make small leaflet api adjustments for esri viewer
* Set index_map labels natively
* Drop leaflet-label-src dependency

### CODE REVIEW

**Comment by eliotjordan** [comment]
@ewlarson This PR needs a rebase to get the circle ci running.

**Comment by mejackreed** [comment]
Do we want to ship a 1.9 release without the breaking changes first?

**Comment by eliotjordan** [comment]
@mejackreed Are suggesting this should be a 1.10 release or it should released as part of 2.0 with the blacklight 7 updates?

**Comment by ewlarson** [comment]
@mejackreed What changes here break current functionality? 
@eliotjordan was hoping this would make the 1.9 release, assuming 2.0 is BL7 support.

**Comment by mejackreed** [comment]
I was thinking about the leaflet version upgrade potentially being troublesome for some. Perhaps its not though.

**Comment by eliotjordan** [comment]
I'm not sure what was up with CI, so I rebased again and force pushed. Hopefully that helps.

**Pull request merged**
