### PR TITLE
add configurable basemap

### PR DESCRIPTION
**Pull request by mejackreed**
Adds in the ability to configure the basemap. This functionality can be extended in a user's own app:

in a GeoBlacklight apps `app/assets/javascripts/geoblacklight.js`
```javascript
GeoBlacklight.Viewer.Map = GeoBlacklight.Viewer.Map.extend({
  selectBasemap: function() {
    var _this = this;
    return //anything!;
  }
});
```

or add more basemaps:
```javascript
GeoBlacklight.Viewer.Map = GeoBlacklight.Viewer.Map.extend({
  basemap: {
    stamenWatercolor: L.tileLayer(
      'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.{ext}', {
        attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        subdomains: 'abcd',
        minZoom: 1,
        maxZoom: 16,
        ext: 'png',
        worldCopyJump: true
      }
    )
  }
});
```

screen shot 2015-04-18 at 10 07 48 am

### CODE REVIEW

**Comment by eliotjordan** [comment]
@mejackreed ++1 for this PR. I did have a few issues. Because of the way the inheritance works here, I think, when you add a new basemap, it's not available in the WMS item show page. You have to add a Viewer.Wms code block in addition to the Viewer.Map code block.
```
GeoBlacklight.Viewer.Wms = GeoBlacklight.Viewer.Wms.extend({ ...
```
I fiddled with this for a few hours and came up with the idea of adding a GeoBlacklight.Basemaps object to the project. This is nice because you don't have to override all the basemaps to add a new item (but you can if you want).
```
// Add new basemap to the list
GeoBlacklight.Basemaps['stamenWatercolor'] = L.tileLayer(
  'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.{ext}', {
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    subdomains: 'abcd',
    minZoom: 1,
    maxZoom: 16,
    ext: 'png',
    worldCopyJump: true
});
```

config-basemap-refine branch - let me know what you think

[basemaps.js](https://github.com/geoblacklight/geoblacklight/blob/config-basemap-refine/app/assets/javascripts/geoblacklight/basemaps.js)

[map.js](https://github.com/geoblacklight/geoblacklight/blob/config-basemap-refine/app/assets/javascripts/geoblacklight/viewers/map.js#L54)

[geoblacklight.js](https://github.com/geoblacklight/geoblacklight/blob/config-basemap-refine/lib/generators/geoblacklight/templates/geoblacklight.js#L2)

**Comment by mejackreed** [comment]
@eliotjordan +1 on your approach! Can you create a pull request to this one?

**Comment by eliotjordan** [comment]
@mejackreed In the hopper. #326

**Comment by mejackreed** [comment]
@eliotjordan thanks... merged!

**Comment by eliotjordan** [comment]
Any other comments/suggestions? If not, I'll merge.

**Comment by mejackreed** [comment]
:+1: :shipit:

**Pull request merged**
