### PR TITLE
Blacklight 7.25 compatible filter changes

### PR DESCRIPTION
**Pull request by barmintor**
add Blacklight 7.25+ compatible changes to `Geoblacklight::BboxFilterField`
avoid deprecated behaviors

### CODE REVIEW

**Comment by barmintor** [comment]
Some of these changes are not strictly necessary if https://github.com/projectblacklight/blacklight/pull/2715 is released, but they remove the use of a deprecated helper.

**Comment by barmintor** [comment]
Added a commit to address some linter failures in specs, though they are outside the scope of the change.

**Review by ewlarson — APPROVED** [review]
Hi @barmintor - Thanks for looking out for GeoBlacklight here. Much appreciated!

**Comment by ewlarson** [comment]
Just a quick note to say the changes in the PR need to be added to main and released in new v4 and v3 versions of GBL.

**Review by eliotjordan — APPROVED** [review]

**Pull request merged**
