### PR TITLE
Center the search bar

### PR DESCRIPTION
**Pull request by marlo-longley**
According to the screenshots in the thread for PR #1441, the search bar should be centered, but correct me if I am wrong@!

### Before

Screenshot 2024-08-07 at 10 00 51
Screenshot 2024-08-07 at 10 09 16

### After

Screenshot 2024-08-14 at 13 53 11
Screenshot 2024-08-14 at 13 53 19

### CODE REVIEW

**Comment by dnoneill** [comment]
The search bar shouldn't be showing up on the homepage above the banner. It should be below the banner.

**Comment by dnoneill** [comment]
Also the old main looked like this: https://github.com/geoblacklight/geoblacklight/pull/1400 so I think it was supposed to be off center?

**Comment by marlo-longley** [comment]
@dnoneill Thanks for the reference. OK, based on that I see that the search results page should stay as is.
The homepage should 1. move the search bar beneath the "Explore and Discover" banner and 2. center the search bar.
If that sounds right I will update this PR.

**Comment by eliotjordan** [comment]
@dnoneill Can we move the search bar below the Hero element text to match the existing GBL design?

**Comment by marlo-longley** [comment]
@dnoneill @eliotjordan please see updated "After" screenshots in the top comment of this PR. Should be good!

**Review by eliotjordan — APPROVED** [review]

**Pull request merged**
