### PR TITLE
Create CODE_OF_CODUCT.md

### PR DESCRIPTION
**Pull request by molliewebb**
Creating code of conduct page.

### CODE REVIEW

**Comment by mejackreed** [comment]
💯 👍 👏

**Comment by molliewebb** [comment]
@KarenMajewicz  Good catch!  What if we linked to the Google Group like we do on the "Connect" page... or we could just link to the "Connect" page?

**Comment by KarenMajewicz** [comment]
The Connect page/Google Group are all links to public forums.  If the purpose of the sentence is to advise someone on what to do if they need to report "unacceptable behavior," I don't really know that these forums are helpful links?  Ack, not trying to be nit-picky, just logical.

**Comment by molliewebb** [comment]
Could we set up an alias email with a distribution list to the governance committee or whoever else would like to be on the list?

**Comment by KarenMajewicz** [comment]
The alias email might be a good idea. I will add this to our GBL Community Meeting agenda set for next week.

**Comment by mejackreed** [comment]
@molliewebb do you mind updating this PR with the new email address? geoblacklight-code-of-conduct@googlegroups.com

**Pull request merged**
