### PR TITLE
Adds URI constant for data_dictionary (/documentation download)

### PR DESCRIPTION
**Pull request by sgbalogh**
https://github.com/geoblacklight/geoblacklight/issues/424

### CODE REVIEW

**Comment by mejackreed** [comment]
Awesome! Is there any UI functionality we should add also in this PR?

Potentially also update http://geoblacklight.org/tutorial/2015/02/09/geoblacklight-overview.html?

**Comment by sgbalogh** [comment]
Happy to add a tool partial for it, if everyone is OK with that being part of GeoBlacklight core: 
screen shot 2016-08-01 at 4 35 34 pm

Any suggestions for default text? Perhaps just `Data Dictionary`, or even more generally just `Documentation`?

**Comment by mejackreed** [comment]
👍 all the way on your suggestions.

**Comment by drh-stanford** [comment]
maybe "Detailed Documentation" or just "Documention"

**Comment by sgbalogh** [comment]
@drh-stanford in the PR the [default](https://github.com/geoblacklight/geoblacklight/blob/376e99566269c1cfd74c0e19142185ca1d8ad02f/config/locales/geoblacklight.en.yml#L33) is set to `Documentation`; is that ok?

**Comment by eliotjordan** [comment]
Excellent work. ✨

**Pull request merged**
