### PR TITLE
Update to Engine Cart v0.8 in preparation of Blacklight 6

### PR DESCRIPTION
**Pull request by mejackreed**
Note to developers: this changes the location of the test app. Test app location now at `.internal_test_app`

### CODE REVIEW

**Comment by cbeer** [comment]
What about https://github.com/geoblacklight/geoblacklight/blob/a783f63e91f9042d5bbb3042b1f8edeadb31e441/Rakefile#L32?

**Comment by mejackreed** [comment]
Thanks @cbeer for pointing that out. Now updated.

**Comment by cbeer** [comment]
:shipit: ?

**Comment by mejackreed** [comment]
:shipit: !

**Pull request merged**
