### PR TITLE
Add support for complex geometries

### LINKED ISSUE #524: add support for geometry-based (i.e., polygon) bounding regions
Currently in 1.x GeoBlacklight only supports rectangular bounding boxes

### LINKED ISSUE #534: Support JTS geometry in a configurable way
### Descriptive summary

A prerequisite to #524 and #533. 

JTS (Java Topology Suite) should be able to easily be added to an adopter's solr configuration. This should be optional and part of an automatic generator that can be turned on with an argument passed to the generator.

Some exploratory work was started here: https://github.com/geoblacklight/geoblacklight/compare/add-jts-to-install?expand=1

### LINKED ISSUE #616: Bounding Boxes crossing the 180th meridian display horizontally flipped
### Descriptive summary

When the bounding box straddles the 180th meridian, the search results will show the footprint incorrectly. This is a known bug, but perhaps we can address or at least document it to warn people of the behavior.

Examples:
https://geo.btaa.org/?utf8=%E2%9C%93&f%5Bdct_isPartOf_sm%5D%5B%5D=John+R.+Borchert+Map+Library&per_page=20&search_field=all_fields&q=ortelius

https://maps.princeton.edu/?utf8=%E2%9C%93&featured=scanned_maps&search_field=all_fields&q=East+Asia+and+Oceania
  

### Related work

VecNet issues:
https://github.com/vecnet/dl-discovery/issues/12
https://github.com/vecnet/dl-discovery/issues/61

Big 10 issue:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/84

### PR DESCRIPTION
**Pull request by eliotjordan**
- Adds opt-in support for complex WKT geometries.
- When enabled, can fix issues with displaying bounding boxes that cross the anti-meridian.
- In the future, we will probably wan't to require support via JTS (With plenty of advanced warning, I think this is achievable). 

Follow Up Tasks:
- #1038 Document how to add support via Geo3D and JTS
- #1039 Document how to construct geometries for bounding boxes that cross the anti-meridian
- (future task) #1037 Add rake task to copy JTS into solr-wrapper

Closes #524
Closes #534
Closes #616

### CODE REVIEW

**Comment by mejackreed** [comment]
Was Geo3D insufficient?

**Comment by eliotjordan** [comment]
@mejackreed Yeah. :( It doesn't work with the overlap ratio boosting. I'm not sure why, it's undocumented as far as I can tell.

**Comment by mejackreed** [comment]
I wonder if we could get an upstream issue started?

_Could_ we support Geo3D and the additional geometry parsing in an opt-in way in GeoBlacklight v3.x ? That way someone could opt in to the current behavior without needing to go full JTS yet? (with the caveat that bbox overlap ratio doesn't work?)

**Comment by eliotjordan** [comment]
@mejackreed The PR as it stands is agnostic about how one adds polygon support. I was planning on writing documentation to show how to add it via both built-in Geo3D (with overlap ration limitations) and JTS.

**Review by andrewbattista — APPROVED** [review]
We were given a walk through with @eliotjordan and @ewlarson. It all looks great to me, and the tests pass on my machine. Thanks for making headway on a circa 2016 era challenge for us!

**Pull request merged**
