### PR TITLE
1323 remove email downloads from core

### PR DESCRIPTION
**Pull request by yuntianhu**
Descriptive summary
Harvard no longer does email downloads, so the special functionality we built in for Harvard is no longer needed

Expected behavior
We just don't want this code anymore, so this will make that go away.

### CODE REVIEW

**Comment by ewlarson** [comment]
Hi @yuntianhu // There are quite a few more places where this HGL download code needs to be removed from the application: https://github.com/search?q=repo%3Ageoblacklight%2Fgeoblacklight+hgl&type=code&p=1

Also! Tests are correctly failing here, because of the leftover bits of HGL code/specs, too. Please keep working here to pull all the HGL code out and let me know if you need any assistance.

**Comment by yuntianhu** [comment]
@ewlarson thank you Eric. Will do.

**Comment by ewlarson** [comment]
Dumping screenshots of the missing coverage pieces here. Hope this is helpful!

Screenshot 2024-08-14 at 10 42 28 AM
Screenshot 2024-08-14 at 10 42 45 AM
Screenshot 2024-08-14 at 10 42 49 AM
Screenshot 2024-08-14 at 10 43 01 AM

**Comment by yuntianhu** [comment]
@ewlarson  Thank you very much, Eric! It is really helpful. I will try to replicate it on my local server. I won't be in the stand up meeting today, But I will contact you via slack if I some question.

**Comment by yuntianhu** [comment]
@ewlarson sure, will do.

**Comment by yuntianhu** [comment]
@ewlarson branch rebased. it should be up to date to main now.

**Comment by ewlarson** [comment]
Sorry @yuntianhu // Looks like your rebase didn't rebase correctly — your commits are now doubled in fact. Not sure how to rescue that...

I suggest you revert this PR to a draft and create a brand new PR with just one commit including all the changes you intend here. That'll be the cleanest way to move this forward.

**Comment by yuntianhu** [comment]
@ewlarson  will do

**Comment by eliotjordan** [comment]
Closing this PR because https://github.com/geoblacklight/geoblacklight/pull/1518 was approved and merged.

**Pull request closed without merging**
