### PR TITLE
Add JavaScript testing framework Teaspoon

### PR DESCRIPTION
**Pull request by mejackreed**
- enables JavaScript specs (see spec/javascripts/geoblacklight_spec.js)
 - should allow us to start better testing the JavaScript as more complexity is added.
 - uses Jasmine

*Note:* engine_cart:clean && engine_cart:generate will need to be ran

### CODE REVIEW

**Comment by eliotjordan** [comment]
Teaspoon looks nice and seems to play well with GeoBlacklight.

@mejackreed what is/was your reasoning for choosing Jasmine? From what I can tell, both Mocha and Jasmine are similar to RSpec. Jasmine does seem simpler to set up, as Mocha needs additional assertion libraries.

**Comment by mejackreed** [comment]
@eliotjordan Implemented Jasmine because it just seemed easier/simpler to get up and going.

**Comment by mejackreed** [comment]
Also I think it has been kicked around to be added into Blacklight, and the thought was to use Jasmine there as well.

**Comment by eliotjordan** [comment]
The general consensus is that Jasmine is a good way to go, so I'll merge this in.

**Pull request merged**
